name: Playwright Tests
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select test type to run'
        required: true
        default: 'ALL'
        type: choice
        options:
          - ALL
          - UI
          - API

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-types: ${{ steps.set-matrix.outputs.types }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event_name }}" != "workflow_dispatch" ] || [ "${{ github.event.inputs.test_type }}" == "ALL" ]; then
            echo "types=[\"UI\", \"API\"]" >> $GITHUB_OUTPUT
          else
            echo "types=[\"${{ github.event.inputs.test_type }}\"]" >> $GITHUB_OUTPUT
          fi

  playwright-tests:
    needs: setup
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type: ${{ fromJson(needs.setup.outputs.test-types) }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --grep "@${{ matrix.test-type }}"
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.test-type }}
        path: playwright-report/
        retention-days: 30
